FROM python:alpine
LABEL "Maintainer"="satejall@gmail.com"

WORKDIR /user/app

COPY   ./requirements.txt ./
RUN  pip install -r requirements.txt
COPY  ./app ./app
# ENTRYPOINT [ "python" ]

CMD ["ls","-d"]
