FROM python:alpine
LABEL "Maintainer"="satejall@gmail.com"

WORKDIR /user/app

COPY   ./requirements.txt ./
COPY ./main.py ./
RUN  pip install -r requirements.txt
COPY  ./app ./app
ENTRYPOINT [ "python" ]

CMD ["main.py"]
